server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册到eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/HuangZiHua/spring-cloud-config-test.git
          search-paths:
            - spring-cloud-config-test
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

# rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

