server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh       #payment_route 路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务器的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
#            - After=2021-04-26T14:26:00.957+08:00[Asia/Shanghai]   #在配置时间之后生效
#            - Cookie=username,\d+    # key=pattern
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - After=2021-04-26T15:26:00.957+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
